-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 21:14:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_engenharia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_engenharia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_engenharia` DEFAULT CHARACTER SET utf8 ;
USE `banco_engenharia` ;

-- -----------------------------------------------------
-- Table `banco_engenharia`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`ENDERECO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(30) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(60) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`CLIENTE` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(30) NULL,
  `cnpj` VARCHAR(30) NULL,
  `razaosocial` VARCHAR(60) NULL,
  `nome` VARCHAR(60) NULL,
  `inscricaoestadual` VARCHAR(30) NULL,
  `rg` VARCHAR(30) NULL,
  `representante` VARCHAR(60) NULL,
  `situacao` VARCHAR(60) NOT NULL,
  `datanasc` VARCHAR(60) NULL,
  `sexo` VARCHAR(60) NULL,
  `uf_rg` VARCHAR(10) NULL,
  `orgaoexpedidor` VARCHAR(60) NULL,
  `email` VARCHAR(60) NOT NULL,
  `limitecredito` DOUBLE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `ENDERECO_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_CLIENTE_ENDERECO1_idx` (`ENDERECO_id` ASC),
  CONSTRAINT `fk_CLIENTE_ENDERECO1`
    FOREIGN KEY (`ENDERECO_id`)
    REFERENCES `banco_engenharia`.`ENDERECO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`CARGO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`FUNCIONARIO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `rg` VARCHAR(30) NOT NULL,
  `uf_rg` VARCHAR(10) NOT NULL,
  `orgaoexpedidor` VARCHAR(45) NOT NULL,
  `dataexpedicao` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `naturalidade` VARCHAR(45) NOT NULL,
  `datanasc` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `ctps` VARCHAR(30) NOT NULL,
  `dataadmissao` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `salario` DOUBLE NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `CARGO_id` INT NOT NULL,
  `ENDERECO_id` INT NOT NULL,
  PRIMARY KEY (`codigo`, `cpf`),
  INDEX `fk_FUNCIONARIO_CARGO1_idx` (`CARGO_id` ASC),
  INDEX `fk_FUNCIONARIO_ENDERECO1_idx` (`ENDERECO_id` ASC),
  CONSTRAINT `fk_FUNCIONARIO_CARGO1`
    FOREIGN KEY (`CARGO_id`)
    REFERENCES `banco_engenharia`.`CARGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_ENDERECO1`
    FOREIGN KEY (`ENDERECO_id`)
    REFERENCES `banco_engenharia`.`ENDERECO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`FORNECEDOR` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `nome` VARCHAR(60) NULL,
  `razaosocial` VARCHAR(60) NULL,
  `rg` VARCHAR(30) NULL,
  `representante` VARCHAR(60) NULL,
  `uf_rg` VARCHAR(10) NULL,
  `orgaoexpedidor` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `datanasc` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `ramoatividade` VARCHAR(45) NOT NULL,
  `ENDERECO_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_FORNECEDOR_ENDERECO1_idx` (`ENDERECO_id` ASC),
  CONSTRAINT `fk_FORNECEDOR_ENDERECO1`
    FOREIGN KEY (`ENDERECO_id`)
    REFERENCES `banco_engenharia`.`ENDERECO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`UNIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`UNIDADE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`TIPO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_engenharia`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_engenharia`.`PRODUTO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `codigobarras` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `valorcompra` DOUBLE NOT NULL,
  `valorvenda` DOUBLE NOT NULL,
  `lucro` DOUBLE NOT NULL,
  `estoqueminimo` INT NOT NULL,
  `estoquemaximo` INT NOT NULL,
  `UNIDADE_id` INT NOT NULL,
  `TIPO_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_PRODUTO_UNIDADE_idx` (`UNIDADE_id` ASC),
  INDEX `fk_PRODUTO_TIPO1_idx` (`TIPO_id` ASC),
  CONSTRAINT `fk_PRODUTO_UNIDADE`
    FOREIGN KEY (`UNIDADE_id`)
    REFERENCES `banco_engenharia`.`UNIDADE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_TIPO1`
    FOREIGN KEY (`TIPO_id`)
    REFERENCES `banco_engenharia`.`TIPO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
